# Example pubspec.yaml for your package
name: typed_form_fields
description: >-
  Type-safe, universal form field wrapper for Flutter with zero dependencies, high performance, and validation optimizations.

version: 1.3.0

homepage: https://github.com/MurhafMoussa/typed_form_fields
repository: https://github.com/MurhafMoussa/typed_form_fields
issue_tracker: https://github.com/MurhafMoussa/typed_form_fields/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  meta: ^1.9.1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0
  build_runner: ^2.4.12
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  benchmark_harness: ^2.2.2

topics:
  - forms
  - validation
  - type-safety
  - state-management
  - zero-dependencies

screenshots:
  - description: "onSubmitOnly - Validation only on form submission"
    path: assets/onSubmitOnly.webp
  - description: "onSubmitThenRealTime - Validation on submit, then real-time"
    path: assets/onSubmitThenRealTime.webp
  - description: "realTimeOnly - Real-time validation for edited fields"
    path: assets/realTimeOnly.webp
  - description: "allFieldsRealTime - Real-time validation for all fields"
    path: assets/allFieldsRealTime.webp
  - description: "disabled - No validation occurs"
    path: assets/disabled.webp

funding:
  - https://github.com/sponsors/yourusername
