# .github/workflows/dart.yml

name: Dart CI/CD

on:
  pull_request:
    branches: [production, development]
  push:
    branches: [development, production]

jobs:
  # This job runs on all PRs and pushes to development/production
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run analyzer
        run: dart analyze

      - name: Run tests
        run: dart test

  # This job ONLY runs when there is a push to the 'production' branch
  deploy:
    # Condition to run only on a push to the production branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    # Ensures that tests must pass before this job starts
    needs: analyze_and_test

    name: Deploy to pub.dev
    permissions:
      id-token: write # Required for secure pub.dev authentication
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      # Step 1: Authenticate with pub.dev
      - name: Setup publishing credentials
        uses: dart-lang/setup-dart@v1
        with:
          publishing: true

      # Step 2: Publish the package, skipping confirmation prompts
      - name: Publish to pub.dev
        run: dart pub publish --force
